version: "2"

services:
  frontend:
    build: ./frontend
    ports:
     - "8505:8501"
    env_file:
     - .env
    volumes:
      - "./frontend:/app:rw"
    restart: always
  notebook:
    build: .
    ports:
     - "8888:8888"
    env_file:
      - .env
    volumes:
      - "./frontend:/home/jovyan/work:rw"